on: push
name: 🚀 Deploy website on push

jobs:
    web-deploy:
        name: 🎉 Deploy
        runs-on: ubuntu-latest
        steps:
            - name: 🚚 Get latest code
              uses: actions/checkout@v3

            - name: Use Node.js 19
              uses: actions/setup-node@v2
              with:
                  node-version: '19'

            - name: 🔨 Build Project
              env:
                  MONGODB_URI: ${{secrets.MONGODB_URI}}
                  JWT_KEY: ${{secrets.JWT_KEY}}
                  ORIGIN: ${{secrets.ORIGIN}}
                  MONGODB_URI: ${{env.MONGODB_URI}}
                  JWT_KEY: ${{env.JWT_KEY}}
                  ORIGIN: ${{env.ORIGIN}}
              run: |
                  cd nuxt 
                  npm install
                  npm run build
                  echo "hello ${{secrets.JWT_KEY}}"

            - name: 📂 Sync files
              uses: appleboy/scp-action@v0.1.4
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  source: 'nuxt/.output'
                  target: './petitepausecafe'

            - name: start Nuxt server
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.HOST }}
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}
                  port: 22
                  script: |
                      cd petitepausecafe/nuxt
                      pm2 restart petitepausecafe
